### ISSUE TITLE
As a Customer/Guest, I want to pay with my card

### ISSUE THREAD

**Issue by Milles98** [KYH-Net23/PaymentProvider#1]
# Made by Mille Elfver, William Gross & Mousa Chammas

## Acceptance Criterias

- [ ] Customers can fill out fields “card number”, “expiration date” and “cvv number”.
- [ ] Customer input gets validated.
- [ ] If input is valid, payment is processed, a green success message is shown and the customer is redirected to the order confirmation page.
- [ ] If input is invalid, payment is declined and a red error message is shown.

---

## Activity Diagram
[PlantUml Activity Diagram Link](https://www.plantuml.com/plantuml/duml/TP3DJWCn38JlUGfhJwq49yIblLJY1NY5i9djMifFPJk5lZtkBZy5n2MPo3EZppceHR5USbX4s3rrjLOWn4gjqYbU2ghvVSJ-PZf79KN6Q4WqHaaK9cc5RCPNfi3cblHFTkASlRoRA-H4hsmp3Kj9xUK5CeG1RoUMQEm8AHg6EpUSpv_pVU1fiuILec1fl78q4IVAb-sLezBc0js6tVC73pkAj16gIBSydW6VeNGKU4hxUFLGyUCNkJS84ikwTfmCGW_tZwGOMtMMO8sQ90ZvUs8fwmRh1o0hQ5FRJwA4CNFz1qYG229Dlc5G4q_1ZQTmSDrBVWS0) 
![Image](https://github.com/user-attachments/assets/4d0aa454-0d9b-46be-bdc8-152f046e6d84)

---

## Tasks
- [ ] KYH-Net23/Rika#87
  - [ ] Implement “Card Number” field
  - [ ] Implement “Expiration Date” field
  - [ ] Implement “CVV number” field
- [ ] KYH-Net23/PaymentRepo#3
  - [ ] Validate fields, give green message if legitimate input
  - [ ] Give red error message if input is incorrect
- [ ] KYH-Net23/PaymentRepo#4
  - [ ] Implement a connection to the card supplier to process payment.

---

## Test Case Descriptions
- [ ] Test case 1: Successful card payment
- Prerequisites: 
  - Valid card information.
- Steps:
1. Valid card number is written.
2. Valid expiration date is written.
3. Valid CVV number is written.
4. Payment gets processed through the card supplier.
- Expected result:
  - Payment is successful and the customer is redirected to the order confirmation page.

- [ ] Test case 2: Invalid card payment
- Prerequisites: 
  - Invalid card information.
- Steps:
1. Invalid card number is written.
2. Invalid expiration date is written.
3. Invalid CVV number is written.
4. Payment is not processed through the card supplier.
- Expected result:
  - Payment is declined and the customer is shown a red error message.
