### ISSUE TITLE
As a Customer/Guest, I want to pay with invoice.

### ISSUE THREAD

**Issue by WILGROSS** [KYH-Net23/PaymentProvider#10]
# Made by Mille Elfver, William Gross & Mousa Chammas

## **Acceptance Criterias**
- [ ] Customer is shown a confirmation text that payment details will be sent to email.
- [ ] Invoices with payment details are sent to customers' email.
- [ ] Customer is redirected to the order confirmation page.

---

## **Activity Diagram**
[PlantUml Activity Diagram Link](https://www.plantuml.com/plantuml/duml/PP0nJWGn34NxdC8Ne48qqAn4nJ7Cn4Ci9V7Azh9mUxuO1eqqLPBtzRwjN2BPypPw-RsKvzTRf0rnqY2RTENl8JDnViZB8MqS5D9bIQcayzDqaRAwZNzZI3QhSJ8LOhFxf9Ilf6oSkrAg96iFkcllz2uKW9H6Ce3HyRRDGPwDq86CuDBkiP-TuroNghwjp6k2FJuyGLXirYXmp2iWdglwu5IRVzkZubekCYi-wWS0)
![Image](https://github.com/user-attachments/assets/5a66ecb2-974e-4457-9cd4-adf4593166c3)

---

## **Tasks**
- [ ] KYH-Net23/Rika#114
> - [ ] Implement UI for confirmation text that payment details will be sent to email.
> - [ ]  Implement UI for error text if payment details failed to send.
- [x] #15
> - [ ] Email information with how to pay is sent.
> - [ ] Order Details etc.

---

## **Test Case Descriptions**
- [ ] **Test case 1: Invoice gets sent**
- **Prerequisites**
  - Customer has chosen invoice as a payment method.
- **Steps:**

   - 1. Customer navigates to the payment page.
   - 2. Invoice is processed and sent through Azure Communications.

- **Expected result:**
  - Email with information is sent.

- [ ] **Test case 2: Invoice does not get sent**
- **Prerequisites**
  - Customer has chosen an invoice as a payment method.
- **Steps:**

   - 1. Customer goes to the payment page.
   - 2. Invoice is processed through Azure Communications.
   - 3. Azure Communications is down.

- **Expected result:**
  - No email is sent
  - Red error message is shown.
