### ISSUE TITLE
As a Customer/Guest, I want to pay with paypal.

### ISSUE THREAD

**Issue by MosesDaCode** [KYH-Net23/PaymentProvider#11]
# Made by Mille Elfver, William Gross & Mousa Chammas

## **Acceptance Criterias**

- [ ] Customer is redirected to Paypal for processing.
- [ ] If it’s successful, payment is processed, the customer is shown a green success message and is redirected to the order confirmation page.
- [ ] If it's unsuccessful, payment is declined and a red error message is shown.

---

## **Activity Diagram**
[PlantUml Activity Diagram Link](https://www.plantuml.com/plantuml/duml/VKzBRWCX3Drp2Y-JHLTLDyacKY-GAw3XCOC4U6IRIhbzdNIIfghQ3JpC-poVrABOQ3NSG3Yy3pLk42fAt6cDbuPkViyuFlqkKKbHCHdIbRJ66h9mUmWQRE6aluHkAqX5lfJ6j0fFK2LRXCUyR6R7KFBkV8CFXajrJ5UOHzsx09rs5-W-7CvRQj4x6-avrUDGFg0q2z3lDjJy-BTVpEQprvStKapSarBmoYp9f_xEHLgqmdrR4rL1kyu_6oLCjVG_2ecdG8JbkmnwAZauSGqdnwFLJm00) 

![Image](https://github.com/user-attachments/assets/cb446ba5-cf51-442f-b049-6e56ebfd9936)

---

## **Tasks**

- [ ] KYH-Net23/Rika#109
  - [ ] Implement a connection to paypal for payment processing.
- [ ] KYH-Net23/Rika#111
  - [ ] Validate paypal processing.
  - [ ] Give a red error message if there's an issue.
  - [ ] Give a red success message if legitimate.

---

## **Test Case Descriptions**

- [ ] **Test case 1: Successful paypal processing**
    - Prerequisites: 
      - Customer has a paypal account.

    - Steps:
        1. Customer is redirected to paypal.
        2. Paypal tries to process the payment.

    - Expected result:
      - Payment is successful and customer is redirected to order confirmation page

- [ ] **Test case 2: Unsuccessful paypal processing**
    - Prerequisites: 
      - Customer doesn’t have a paypal account.

    - Steps:

        1. Customer is redirected to paypal.
        2. Customer tries to log in.

    - Expected result:
      - Red error message is shown.
