### ISSUE TITLE
As a customer/guest, I want to select a payment option of my choosing before checking out.

### ISSUE THREAD

**Issue by MosesDaCode** [KYH-Net23/PaymentProvider#16]
# Made by Mille Elfver, William Gross & Mousa Chammas

## **Acceptance Criterias**

- [x] Customer is in the checkout process.
- [x] Customer reaches payment methods steps.
- [x] List of available payment options displayed.
- [x] Customer chooses a payment option.
- [x] Customer clicks on the continue button.
---

## **Activity Diagram**
[Plant Uml Activity Diagram Link](https://www.plantuml.com/plantuml/duml/LOz1QWCn34NtFeNECRD9wQgxGa-WsCgCY2mPIvuojwyfII2xp-FnzNNnm1wZIleFQVaS7bQfW-B16mOvX473iv86L8hTYgzf-G1X3x0Ru84iU1LwMTQ2JHsm4nJs9dXIMTFD-dqUmFx8W1kofkNdbtr_HzzuDfHtzgM7SQOraHPuT3t7Pk5yTuYT89i6wo2uZWZJEJK_hOt2NtyL20FhPN8VjM8_rpIzbYwpVrJv0m00)
![Image](https://github.com/user-attachments/assets/6d511456-3f81-4a70-821e-ed42862cfccc)
---

## Sequence Diagram
[PlantUml Sequence Diagram Link](https://www.plantuml.com/plantuml/duml/bPB1Rjim38RlVWgYzs3t7ePcNWy3XZQOdu2LcLY891eIbI5x-ic28yrsXco710d9x_TF-dy9WbwYDGqgOGzj3CAMV3EcibPwH2Vmr0wapXm53dYY9y00jyfKMCuUy6ef_NWVHRCB5PaRVoVsXsz_3gQ_oxdzh-W9MhOsEgqmosSWDwPwqzpym-xpmYCyGpTj2dKLpuf2Q1PJYIesC_I65tr28H26rMPDWqRWgmwZmUkc2G1phIZNlPBm3nAlwKBmNGS1FjuNgCHkOoqfHE_-vS7bAC_5xlw2sk27eGrFhi-RLKeDp84288ppBEVP_AWojV7NaI4bA_s7TvbVoqnJl-Rls3DQdGEm0yLEj8i47r7aeRzsug2zCLygWwRQjYG3zn1cExc_tM6PjMLitdrF7hfeBVfhuTUnAndEbtFzZ2LxH-rj3ZkyMjIcA5HYjp6mv9AUP8nC87XZ6FzpkPgVRk2VyEezU_WqXIb7wDuDf_SqVLxILxJcDm00)

![Image](https://github.com/user-attachments/assets/a52ebb1e-6d82-4504-917a-2e3405a9f80e)
---

## **Tasks**

- [x] #18
  - [x] #19
- [x] KYH-Net23/Rika#76
  - [x] Implement a payment button on the shipping options page to navigate to payment options.
- [x] KYH-Net23/Rika#77
  - [x] Implement a payment page with a list of payment options displayed.
- [x] KYH-Net23/ProductsRepo#163
  - [x] Create card integration from cards API to allow users to write their information and pay with card.
- [ ] KYH-Net23/ProductsRepo#165
  - [ ] Create Swish integration from their APIs to allow users to pay with swish.
- [x] KYH-Net23/ProductsRepo#166
  - [x] Create Paypal integration.
- [x] KYH-Net23/ProductsRepo#167
  - [x] Create logic to allow users to pay using invoices.
- [x] KYH-Net23/ProductsRepo#168
  - [x] Write logic to make sure that inputs are validated.
- [x] KYH-Net23/ProductsRepo#169
  - [x] To send email confirmations.
---

## **Test Case Descriptions**
- [ ] **Test case 1: Customer not choosing a payment method.**
  - **Prerequisites:** 
    - Customer has Added items to the shopping cart.

  - **Steps:**
    1. Customer goes through the checkout process to the payment methods step.
    2. Customer does not select any payment method from the available options.
    3. Customer clicks on the continue button without choosing a payment method.

  - **Expected result:**
    - Continue button should be disabled and the customer remains on the payment methods page until a payment is chosen.

- [ ] **Test case 2: Customer choosing a payment method.**
  - **Prerequisites:** 
    - Customer has Added items to the shopping cart.

  - **Steps:**
    1. Customer goes through the checkout process to the payment methods step.
    2. Customer selects a payment method from the available options.
    3. Customer clicks on the continue button.

  - **Expected result:**
    - Customer gets navigated to Order summary.
