### ISSUE TITLE
As an admin I want to view a specific customer’s orders so I can get an overview of all their orders

### ISSUE THREAD

**Issue by acerd44** [KYH-Net23/PaymentProvider#31]
**Made by Hossén & Oliver**

## Acceptance Criteria
- [ ] Only admins should be able to access/view customer information.
- [ ] The page should display a list of all the customer’s orders that have been placed with relevant and correct order information.
## Tasks
- [ ] KYH-Net23/PaymentProvider#32
- [ ] KYH-Net23/PaymentProvider#33
- [ ] KYH-Net23/PaymentProvider#34
- [ ] KYH-Net23/PaymentProvider#35
- [ ] KYH-Net23/PaymentProvider#36
- [ ] Implement API endpoint for fetching a list of the customer's orders from a database.
- [ ] Implement authorization so only admins can access and view customer information.
- [ ] Implement UI/frontend
  - [ ] Display all orders in a table.
## Test Cases
- [ ] Verify that the list of orders are loaded and displayed properly.
  - Prerequisites: 
    - User is logged in as an administrator.
    - The administrator is on a customer's details page.
  - Steps
    - Click on the "Order History" button on the customer's details page.
  - Expected result: 
    - The system displays a list of the customer's orders properly.
- [ ] Verify that only admins can access and view customer information.
  - Prerequisites:
    - The user attempting to access the page (presumably by URL) is not an administrator or is not logged in.
  - Steps:
      - Enter the URL for the customer's details page or the customer's order history page.
  - Expected results:
      - The user is redirected to a 401 error code page (unauthorized).
      - Display an error message.
- [ ] Verify that an error message is displayed when no orders are fetched or found.
  - Prerequisites:
    - User is logged in as an administrator.
    - The customer has no orders OR the API/microservice for fetching customer is offline or not working.
  - Steps:
    - Navigate to the customer's details page
    - Click on the "Order History" button.
  - Expected results:
    - The system displays an error message "No orders found".
## Activity Diagram
![Image](https://i.imgur.com/5lM8wjg.png)
