### ISSUE TITLE
As a Customer/Guest, I want to pay with swish.

### ISSUE THREAD

**Issue by MosesDaCode** [KYH-Net23/PaymentProvider#5]
# Made by Mille Elfver, William Gross & Mousa Chammas

## **Acceptance Criterias**
- [ ] Customer enters phone number that is connected to swish
- [ ] Customer Opens swish either from the form page or manually.
- [ ] Customer confirms payment with bankId
- [ ] Customer receives a confirmation message if payment is successful..
- [ ] Customer receives an error message if payment is declined.

---

## **Activity Diagram**
[PlantUml Activity Diagram Link](https://www.plantuml.com/plantuml/duml/TP2zRY9148JpUOeI4GGNdIw11Dr55zcIds2zKyksc9zLTm-8j_TYi05RZkQJUghdczgQT-ejf_0EOVslcTTCXHXgmTITCelFvuwRk-dO6Oo9lJF2Zc8Zmg0rVmOoVQpHlWK7ISbGcy_4574K7x5m9avZBKHf-PMwk8_qIVgzOV4qiU3b_DRZk9P1D1iEqk5lL_R_uoR8iBmWn62jxsasjBI2ZonOdcYhi7w-kefXqdg-mdY_MTbJ3ZJib2mVQv1fzkLNOb16qKiVtU1K_Fxr1yRPBXg2LrIDDzlEfPPhEKn6B4jzD8hiavGVX9GHLArwas69CWJpEeNjp2sdDm00)

![Image](https://github.com/user-attachments/assets/7f619c66-3b4f-4ff0-8298-c21eaf337042)

---

## **Tasks**

- [ ] KYH-Net23/Rika#90
  - [ ] Add input field for phone number.
- [ ] KYH-Net23/Rika#91
  - [ ] Add Open swish button
- [ ] KYH-Net23/Rika#92
  - [ ] Implement validation for phone number.
- [ ] KYH-Net23/Rika#93
  - [ ] Implement logic for the button to redirect to the swish app.

---

## **Test Case Descriptions**

- [ ] **Test case 1: Customer enters non numeric characters**
    - Prerequisites: 
      - Customer picked swish option

    - Steps:
        1. Customer types in a letter 

    - Expected result:
      - Validation error message pops up under the phone number form

- [ ] **Test case 2: Swish payment successful**
    - Prerequisites: 
      - Customer have a bank account connected to swish

    - Steps:

        1. Customer enters a valid phone number.
        2. Customer clicks on the open swish button.
        3. Customer follows instructions and pays successfully.
        4. Customer gets redirected to swish page.

    - Expected result:
      - Customer gets a green success message and gets redirected to the order confirmation page after 3-5 sec.

- [ ] **Test case 3: Swish payment declined**
    - Prerequisites: 
      - Customers have the swish app.

    - Steps:

        1. Customer enters a valid phone number.
        2. Customer clicks on the open swish button
        3. Customer gets redirected to the swish app.
        4. Customers sees that the phone number is not connected to swish app

    - Expected result:
      - Customer gets redirected back to swish page and receive an red error message

**Comment by acerd44** [comment]
Not possible with Stripe
